n = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(n)}')
print(f'Só tem espaço? {n.isspace()}')
print(f'É um número? {n.isnumeric()}')
print(f'É alfabético? {n.isalpha()}')
print(f'É alfanumérico? {n.isalnum()}')
print(f'Está em maiúsculo? {n.isupper()}')
print(f'Está em minúsculo? {n.islower()}')
print(f'Está capitalizada? {n.istitle()}')

